[package]
name = "fever-dream-inc"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.18.0"
bevy_egui = "0.39.1"
rand = "0.10.0"
rhai = "1.24.0"
serde = "1.0.228"
wasm-bindgen = "0.2.108"
web-sys = "0.3.85"
